### ISSUE TITLE
Desenvolvimento de Casos de Uso

### ISSUE THREAD

**Issue by fabrifs** [fabrifs/mackpresenca#1]
Objetivo: Desenvolver Diagrama de Casos de Uso assim como especificação do caso de uso

**Comment by YouHaveFailedThisCity** [comment]
Desenvolvido na semana de 21/03

**Comment by fabrifs** [comment]
Para consulta:
(https://github.com/fabrifs/mackpresenca/files/211326/Casos_De_Uso.zip)
![casos de uso](https://cloud.githubusercontent.com/assets/9977998/14404651/4bd99486-fe52-11e5-9841-12b15324908a.png)
