### ISSUE TITLE
Desenvolver Diagrama de Classes

### ISSUE THREAD

**Issue by fabrifs** [fabrifs/mackpresenca#5]
Objetivo: Desenvolver diagrama de classes.

**Comment by YouHaveFailedThisCity** [comment]
Desenvolvido em 08/04

**Comment by fabrifs** [comment]
Diagrama feito:
![diagramaclassesdom](https://cloud.githubusercontent.com/assets/9977998/14404635/f78b5126-fe51-11e5-8797-53edd67041ab.jpg)

**Comment by fabrifs** [comment]
Diagrama para abrir com Astah:

[DiagramaClassesDomin.zip](https://github.com/fabrifs/mackpresenca/files/211325/DiagramaClassesDomin.zip)
